### ISSUE TITLE
El código bajo prueba no cumple con el mínimo de complejidad

### ISSUE THREAD

**Issue by evolentini** [estanislaocrivos/CESE_TSSE_TP3#1]
Para el desarrollo del TP se pido un código bajo prueba real que efectuara algún tipo de procesamiento. El código utilizado solo realiza cinco asignaciones a variables y la llamada a tres funciones en forma transparente. La única complejidad en el TP está en el uso de Mock para validad las llamadas a las funciones de capa baja. Por esta razon la calificación del TP es de 5.

**Comment by estanislaocrivos** [comment]
Hola Esteban. No estaba al tanto del requerimiento de nivel de complejidad del programa a entregar. En principio me basé en la consigna de utilizar un módulo que forme parte del firmware para el Proyecto Final y en ese sentido me pareció mas valioso seguir este camino antes que implementar un sistema propio para el TP. De todos modos, a pesar de su baja complejidad, el módulo merece ser testeado y así lo fue también como parte del flujo de trabajo en mi empresa, por ende pensé que serviría para el trabajo. Gracias por tu comentario. Saludos.
